server:
  PORT: 8000

spring:
  datasource:
    url: jdbc:h2:file:~/Porn/porn-db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
#      properties.hibernate.generate_statistics: true
  h2:
    console:
      enabled: true
      path: /h2-console
